export const LOGIN_ACTION = 'LOGIN_ACTION';
export const REGISTER_ACTION = 'REGISTER_ACTION';
export const ADD_POST_ACTION = 'ADD_POST_ACTION';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const FILTER_ACTION = 'FILTER_ACTION';
export const INCOMING_POST_ACTION = 'INCOMING_POST_ACTION';

